# Generated by Django 3.0.2 on 2020-01-30 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('two', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16)),
                ('age', models.IntegerField(default=18)),
                ('bid', models.CharField(max_length=16)),
            ],
        ),
    ]
